# Arduino Make file
#
# Requires https://github.com/sudar/Arduino-Makefile
# Environment variable ARDUINO_DIR must be set and point to an installed arduino distribution

BOARD_TAG   = nano
BOARD_SUB   = atmega328
ARDUINO_LIBS = Auto485 CMRI Servo

include /usr/share/arduino/Arduino.mk
